### ISSUE TITLE
ssr+无法导入节点配置

### ISSUE THREAD

**Issue by Benjamin23333** [QiuSimons/R2S_OP_SSRP#1]
今天我刷了这个项目的action里的固件，无法通过导入配置信息按钮导入节点。
具体表现为点击按钮->出现对话框->粘贴节点链接->确定->无反应（并未导入节点）。我试了其他的固件，没有这个问题

**Comment by fanck0605** [comment]
使用姿势
1. 添加你要的订阅链接
2. 再在最后加一行空行
3. 右下角点一下保存并应用
4. 更新所有订阅服务器节点

另外附上 GitHub 项目使用姿势
1. 打开项目主页
2. 仔细阅读 README

**Comment by Benjamin23333** [comment]
难道只能像redme.md中说的那样订阅而不能只是单纯的导入节点配置么？

**Comment by QiuSimons** [comment]
> 难道只能像readme.md中说的那样订阅而不能只是单纯的导入节点配置么？

https://github.com/fw876/helloworld
这个项目没有完全适配19.07的luci，在那边提issue就好。
然后我应该会抽时间看怎么临时解决一下

**Comment by QiuSimons** [comment]
尝试性的进行了修复，等最新的action出来就行了
